# URL de conexão com o banco de dados (substitua 'nome_do_seu_banco' pelo nome real do banco)
spring.datasource.url=jdbc:postgresql://localhost:5432/bancoCaps

# Credenciais de acesso ao PostgreSQL
spring.datasource.username=postgres
spring.datasource.password=admin

# Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
# update: Cria as tabelas se não existirem e altera a estrutura caso haja mudanças nas entidades
spring.jpa.hibernate.ddl-auto=update

# Exibe os comandos SQL gerados pelo Hibernate no console (útil para desenvolvimento)
spring.jpa.show-sql=true

# Formata o SQL exibido no console para torná-lo legível
spring.jpa.properties.hibernate.format_sql=true

# Dialeto específico do PostgreSQL para otimização das queries
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect